# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - medicalchatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://medicalchatbotregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_217ecbc37cdd4dd9a37160a78df4263a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_29acb3b925cc4f3ba7f024c10f53241c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: medicalchatbotregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_217ecbc37cdd4dd9a37160a78df4263a }}/medchatapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'medicalchatbot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5810568a2b584339ba6136164c449e90 }}
        images: 'medicalchatbotregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_217ecbc37cdd4dd9a37160a78df4263a }}/medchatapp:${{ github.sha }}'